// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./../layout/baseLayout/baseHeader.vue')['default']
    BaseLayout: typeof import('./../layout/baseLayout/index.vue')['default']
    BaseMain: typeof import('./../layout/baseLayout/baseMain.vue')['default']
    BaseSider: typeof import('./../layout/baseLayout/baseSider.vue')['default']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
